all:
	(cd Clock && make install)
	(cd Test_1 && make)
	(cd Test_2* && make)
	(cd Test_3* && make)


clean:
	(cd Clock && make clean)
	(cd Test_1 && make clean)
	(cd Test_2* && make clean)
	(cd Test_3* && make clean)
	rm -rf h lib
